# Site settings
title: Batida do Coração
email: tiago@geteloquent.com
description: > # this means to ignore newlines until "baseurl:"
  Batida do Coração é um iniciativa para estimular a doação de sangue para 
  encher os bancos públicos antes do carnaval.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
